export const scaleFactor = 4;

export const dialogueData = 
    {
        "pc": "This is my PC. I work mostly in <b>JavaScript/TypeScript</b> these days. I specialize in <b>full-stack development</b> with frameworks like <b>Next.js</b> and tools like <b>React</b>, <b>Redux</b>, and <b>MongoDB</b>. I've also worked on <b>AI projects</b>. Here is my <a href='https://github.com/tuhinkairi' target='_blank'>GitHub</a>!",
        "cs-degree": "Although my degree is in <b>Zoology</b> from Kazi Nazrul University, my passion for <b>technology</b> has driven me to become a skilled <b>full-stack developer</b>. My education also includes a <b>Diploma in Information Technology Applications</b>, which laid the foundation for my programming journey.",
        "sofa-table": "That's my TV. I've been watching <b>tech creators</b> like <a href='https://www.youtube.com/@harkirat1' target='_blank'>Harkirat Singh</a>, <a href='https://www.youtube.com/@freecodecamp' target='_blank'>freeCodeCamp</a>, <a href='https://www.youtube.com/@javascriptmastery' target='_blank'>JavaScript Mastery</a>, and <a href='https://www.youtube.com/@CodeWithHarry' target='_blank'>CodeWithHarry</a> etc.",
        "tv": "That's my TV. I've been watching <b>tech creators</b> like <a href='https://www.youtube.com/@harkirat1' target='_blank'>Harkirat Singh</a>, <a href='https://www.youtube.com/@freecodecamp' target='_blank'>freeCodeCamp</a>, <a href='https://www.youtube.com/@javascriptmastery' target='_blank'>JavaScript Mastery</a>, and <a href='https://www.youtube.com/@CodeWithHarry' target='_blank'>CodeWithHarry</a>.",
        "bed": "This is where I sleep. My best ideas often strike here, like when I designed an <b>AI Medical Assistance Tool</b> or optimized my <b>MERN e-commerce platform</b> for better performance.",
        "resume": "This is my desk and on it is my <b>resume</b>. <a href='https://drive.google.com/file/d/1vO5iPFQWqZuyoxhENngj8nYVJlLWenvs/view?usp=sharing' target='_blank'>Check it out</a>! Contact me at <a href='mailto:tuhinkairii@gmail.com?body=Dear%20Tuhin Kairi,%20Would%20you%20like%20to%20discuss%20the%20upcoming%20project.%0AThank%20you.' target='_blank'>tuhinkairii@gmail.com</a> if you have interesting opportunities!",
        "projects": "Info about my projects: I've worked on several exciting ones like a <b>Medical Assistance Tool</b> using <b>React</b>, <b>NodeJS</b>, and <b>GPT-2</b>, <b>RealTime ChatApp</b> with <b>Next.js</b>, Convex, an <b>E-commerce</b> platform built with the <b>MERN stack</b>, and a <b>Vitals Abnormality Detection</b> system with <b>TensorFlow</b> and <b>Scikit-learn</b>. Learn more on my <a href='https://github.com/tuhinkairi' target='_blank'>GitHub</a>.",
        "library": "There are a lot of <b>programming books</b> on my shelves. While I compulsively buy technical books, my learning often comes from <b>hands-on projects</b>. My favorite topics include <b>AI</b>, <b>responsive design</b>, and <b>backend architecture</b>.",
        "achievements": "🏆 I'm proud of: Secured 🥉 in the <b>Hooghly District Kickboxing Championship</b>, ranked <b>7th</b> for our <b>AI Medical Assistant</b> at the Evolumin Hackathon, and reached the finals of the <b>Masterstack 3.0 Hackathon</b> with our <b>Smart Energy Management System</b> 🚀 at <b>ISM Dhanbad</b>.",
        "exit": "If you want to exit <b>Tuhin's portfolio</b>, just close the tab."
      }
      